<?php
array(
array(['jurusan_id'] => 'SMA00000', ['nama_jurusan'] => 'Umum',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00', ['nama_jurusan'] => 'Umum',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '10', ['nama_jurusan'] => 'Teknologi dan Rekayasa',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15', ['nama_jurusan'] => 'Teknologi Informasi dan Komunikasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20', ['nama_jurusan'] => 'Kesehatan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25', ['nama_jurusan'] => 'Agribisnis dan Agroteknologi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30', ['nama_jurusan'] => 'Perikanan dan Kelautan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35', ['nama_jurusan'] => 'Bisnis dan Manajemen',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40', ['nama_jurusan'] => 'Pariwisata',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45', ['nama_jurusan'] => 'Seni Rupa dan Kriya',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50', ['nama_jurusan'] => 'Seni Pertunjukan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55', ['nama_jurusan'] => 'Seni, Kerajinan dan Pariwisata',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '90900001', ['nama_jurusan'] => 'A - Tunanetra',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900002', ['nama_jurusan'] => 'B - Tunarungu',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900003', ['nama_jurusan'] => 'C - Tunagrahita ringan',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900004', ['nama_jurusan'] => 'C1 - Tunagrahita sedang',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900005', ['nama_jurusan'] => 'D - Tunadaksa ringan',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900006', ['nama_jurusan'] => 'D1 - Tunadaksa sedang',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900007', ['nama_jurusan'] => 'E - Tunalaras',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900008', ['nama_jurusan'] => 'F - Tunawicara',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900009', ['nama_jurusan'] => 'H - Hiperaktif',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900011', ['nama_jurusan'] => 'J - Bakat Istimewa',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900012', ['nama_jurusan'] => 'K - Kesulitan Belajar',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900013', ['nama_jurusan'] => 'N - Narkoba',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900014', ['nama_jurusan'] => 'O - Indigo',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900015', ['nama_jurusan'] => 'P - Down Syndrome',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '90900016', ['nama_jurusan'] => 'Q - Autis',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '1 ', ['nama_jurusan'] => 'IPA',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '2 ', ['nama_jurusan'] => 'IPS',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '3 ', ['nama_jurusan'] => 'Lainnya',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => 'SMK99999', ['nama_jurusan'] => 'Lainnya',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '00000', ['nama_jurusan'] => 'Umum',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000051', ['nama_jurusan'] => 'Bahasa',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '10010', ['nama_jurusan'] => 'Teknik Bangunan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10012', ['nama_jurusan'] => 'Teknik Furnitur',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10014', ['nama_jurusan'] => 'Teknik Plambing dan Sanitasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10016', ['nama_jurusan'] => 'Geomatika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10018', ['nama_jurusan'] => 'Teknik Survey dan Pemetaan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020', ['nama_jurusan'] => 'Teknik Ketenagalistrikan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10022', ['nama_jurusan'] => 'Teknik Pendinginan dan Tata Udara',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10024', ['nama_jurusan'] => 'Teknik Mesin',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10026', ['nama_jurusan'] => 'Teknologi Pesawat Udara',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10028', ['nama_jurusan'] => 'Teknik Grafika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10030', ['nama_jurusan'] => 'Teknik Instrumentasi Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10032', ['nama_jurusan'] => 'Instrumentasi Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10034', ['nama_jurusan'] => 'Teknik Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10036', ['nama_jurusan'] => 'Teknologi Tekstil',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10038', ['nama_jurusan'] => 'Teknik Perminyakan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10040', ['nama_jurusan'] => 'Geologi Pertambangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10042', ['nama_jurusan'] => 'Teknik Kimia',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10044', ['nama_jurusan'] => 'Teknik Otomotif',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046', ['nama_jurusan'] => 'Teknik Perkapalan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10048', ['nama_jurusan'] => 'Teknik Elektronika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10050', ['nama_jurusan'] => 'Teknik Energi Terbarukan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15052', ['nama_jurusan'] => 'Teknik Komputer dan Informatika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15054', ['nama_jurusan'] => 'Teknik Telekomunikasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15056', ['nama_jurusan'] => 'Teknik Broadcasting',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20058', ['nama_jurusan'] => 'Kesehatan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20060', ['nama_jurusan'] => 'Pekerjaan Sosial',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20062', ['nama_jurusan'] => 'Perawatan Sosial',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25066', ['nama_jurusan'] => 'Penyuluhan Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25068', ['nama_jurusan'] => 'Agribisnis Produksi Ternak',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25070', ['nama_jurusan'] => 'Agribisnis Hasil Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25072', ['nama_jurusan'] => 'Agribisnis Produksi Sumberdaya Perairan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25074', ['nama_jurusan'] => 'Mekanisasi Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25076', ['nama_jurusan'] => 'Kesehatan Hewan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25078', ['nama_jurusan'] => 'Agribisnis Pengolahan Hasil Pertanian dan Perikanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25080', ['nama_jurusan'] => 'Kehutanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30082', ['nama_jurusan'] => 'Teknologi Penangkapan Ikan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '00000100', ['nama_jurusan'] => 'Ilmu Pengetahuan Sosial',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000105', ['nama_jurusan'] => 'Bahasa dan Budaya',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000010', ['nama_jurusan'] => 'Pendidikan Agama',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000015', ['nama_jurusan'] => 'Pendidikan Kewarganegaraan (PKn)',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000020', ['nama_jurusan'] => 'Bahasa dan Sastra Indonesia',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000025', ['nama_jurusan'] => 'Bahasa Inggris',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000030', ['nama_jurusan'] => 'Bahasa Asing Lain',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000040', ['nama_jurusan'] => 'Matematika',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000045', ['nama_jurusan'] => 'Ilmu Pengetahuan Alam (IPA)',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000050', ['nama_jurusan'] => 'Ilmu Pengetahuan Sosial (IPS)',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000055', ['nama_jurusan'] => 'Seni dan Budaya',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000060', ['nama_jurusan'] => 'Bimbingan dan Konseling/Konselor (BP/BK)',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000065', ['nama_jurusan'] => 'Muatan Lokal',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000070', ['nama_jurusan'] => 'Pendidikan Keterampilan',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000075', ['nama_jurusan'] => 'Pengembangan Diri',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000085', ['nama_jurusan'] => 'Komputer',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000090', ['nama_jurusan'] => 'Kewirausahaan',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000110', ['nama_jurusan'] => 'Guru Kelas PAUD/TK/RA',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000115', ['nama_jurusan'] => 'Guru Kelas SD/MI/SDLB',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000120', ['nama_jurusan'] => 'Pendidikan Luar Sekolah',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '10010125', ['nama_jurusan'] => 'Teknik Konstruksi Baja',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10010130', ['nama_jurusan'] => 'Teknik Konstruksi Kayu',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10010135', ['nama_jurusan'] => 'Teknik Konstruksi Batu dan Beton',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10010140', ['nama_jurusan'] => 'Teknik Gambar Bangunan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10012145', ['nama_jurusan'] => 'Teknik Furnitur',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10014150', ['nama_jurusan'] => 'Teknik Plambing dan Sanitasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10016155', ['nama_jurusan'] => 'Geomatika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10018160', ['nama_jurusan'] => 'Teknik Survey dan Pemetaan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020165', ['nama_jurusan'] => 'Teknik Pembangkit Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020170', ['nama_jurusan'] => 'Teknik Jaringan Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020175', ['nama_jurusan'] => 'Teknik Instalasi Pemanfaatan Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020180', ['nama_jurusan'] => 'Teknik Otomasi Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020185', ['nama_jurusan'] => 'Teknik Pendingin dan Tata Udara',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020195', ['nama_jurusan'] => 'Teknik Distribusi Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020200', ['nama_jurusan'] => 'Teknik Transmisi Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10020205', ['nama_jurusan'] => 'Teknik Instalasi Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10024210', ['nama_jurusan'] => 'Teknik Pemesinan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10024215', ['nama_jurusan'] => 'Teknik Pengelasan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10024220', ['nama_jurusan'] => 'Teknik Fabrikasi Logam',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10024225', ['nama_jurusan'] => 'Teknik Pengecoran Logam',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10024230', ['nama_jurusan'] => 'Teknik Pemeliharaan Mekanik Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10024235', ['nama_jurusan'] => 'Teknik Gambar Mesin',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10024240', ['nama_jurusan'] => 'Teknik Pemeliharaan Mekanik Mesin',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10026245', ['nama_jurusan'] => 'Pemeliharaan dan Perbaikan Motor dan Rangka Pesawat Udara',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30084', ['nama_jurusan'] => 'Teknologi dan Produksi Perikanan Budidaya',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30086', ['nama_jurusan'] => 'Pelayaran',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35088', ['nama_jurusan'] => 'Administrasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35090', ['nama_jurusan'] => 'Keuangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35092', ['nama_jurusan'] => 'Tata Niaga',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40094', ['nama_jurusan'] => 'Kepariwisataan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40096', ['nama_jurusan'] => 'Tata Boga',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40098', ['nama_jurusan'] => 'Tata Kecantikan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40100', ['nama_jurusan'] => 'Tata Busana',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45102', ['nama_jurusan'] => 'Seni Rupa',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50106', ['nama_jurusan'] => 'Seni Musik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50108', ['nama_jurusan'] => 'Seni Tari',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50110', ['nama_jurusan'] => 'Seni Karawitan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50112', ['nama_jurusan'] => 'Seni Pedalangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50114', ['nama_jurusan'] => 'Seni Teater',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55098', ['nama_jurusan'] => 'Tata Kecantikan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55100', ['nama_jurusan'] => 'Tata Busana',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55102', ['nama_jurusan'] => 'Seni Rupa',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55116', ['nama_jurusan'] => 'Seni Pertunjukan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMA00003', ['nama_jurusan'] => 'Bahasa',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => 'SMA99999', ['nama_jurusan'] => 'Lainnya',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => 'SMLB0001', ['nama_jurusan'] => 'Umum',['untuk_sma'] => 0,['untuk_smk'] => 0),
array(['jurusan_id'] => 'SMLB9999', ['nama_jurusan'] => 'Lainnya',['untuk_sma'] => 0,['untuk_smk'] => 0),
array(['jurusan_id'] => 'SMK10101', ['nama_jurusan'] => 'Teknik Konstruksi Baja',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10102', ['nama_jurusan'] => 'Teknik Konstruksi Kayu',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10103', ['nama_jurusan'] => 'Tekniok Konstruksi Batu dan Beton',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10104', ['nama_jurusan'] => 'Teknik Gambar Bangunan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10201', ['nama_jurusan'] => 'Teknik Furnitur',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10301', ['nama_jurusan'] => 'Teknik Plambing dan Sanitasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10401', ['nama_jurusan'] => 'Geomatika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10501', ['nama_jurusan'] => 'Teknik Pembangkit Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10502', ['nama_jurusan'] => 'Teknik Jaringan Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10504', ['nama_jurusan'] => 'Teknik Otomasi Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10505', ['nama_jurusan'] => 'Teknik Pendingin dan Tata Udara',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10601', ['nama_jurusan'] => 'Teknik Pemesinan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10602', ['nama_jurusan'] => 'Teknik Pengelasan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10603', ['nama_jurusan'] => 'Teknik Fabrikasi Logam',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10604', ['nama_jurusan'] => 'Teknik Pengecoran Logam',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10605', ['nama_jurusan'] => 'Teknik Pemeliharaan Mekanik Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10606', ['nama_jurusan'] => 'Teknik Gambar Mesin',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10702', ['nama_jurusan'] => 'Pemesinan Pesawat Udara (Aircraft Machining)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10704', ['nama_jurusan'] => 'Konstruksi Rangka Pesawat Udara (Airframe Mechanics)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10705', ['nama_jurusan'] => 'Kelistrikan Pesawat Udara (Aircraft Electricity)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10706', ['nama_jurusan'] => 'Elektronika Pesawat Udara (Aviation Electronis)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10801', ['nama_jurusan'] => 'Persiapan Grafika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10802', ['nama_jurusan'] => 'Produksi Grafika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10901', ['nama_jurusan'] => 'Teknik Instrumentasi Logam',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10902', ['nama_jurusan'] => 'Kontrol Proses',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10903', ['nama_jurusan'] => 'Kontrol Mekanik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11001', ['nama_jurusan'] => 'Teknik Pelayanan Produksi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10026250', ['nama_jurusan'] => 'Pemesinan Pesawat Udara (Aircraft Machining)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10026255', ['nama_jurusan'] => 'Konstruksi Badan Pesawat Udara',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10026260', ['nama_jurusan'] => 'Konstruksi Rangka Pesawat Udara (Airframe Mechanics)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10026265', ['nama_jurusan'] => 'Kelistrikan Pesawat Udara (Aircraft Electricity)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10026270', ['nama_jurusan'] => 'Elektronika Pesawat Udara (Aviation Electronis)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10026275', ['nama_jurusan'] => 'Pemeliharaan & Perbaikan Instrumen Elektronika Pesawat Udara',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10028280', ['nama_jurusan'] => 'Persiapan Grafika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10028285', ['nama_jurusan'] => 'Produksi Grafika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10030290', ['nama_jurusan'] => 'Teknik Instrumentasi Logam',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10030295', ['nama_jurusan'] => 'Kontrol Proses',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10030300', ['nama_jurusan'] => 'Kontrol Mekanik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10032305', ['nama_jurusan'] => 'Teknik Instrumentasi Gelas',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10034310', ['nama_jurusan'] => 'Teknik Pelayanan Produksi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10034315', ['nama_jurusan'] => 'Teknik Pergudangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10034320', ['nama_jurusan'] => 'Teknik dan Manajemen Pergudangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10034325', ['nama_jurusan'] => 'Teknik dan Manajemen Produksi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10036340', ['nama_jurusan'] => 'Teknik Pembuatan Benang',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10036345', ['nama_jurusan'] => 'Teknik Pembuatan Kain',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10036350', ['nama_jurusan'] => 'Teknik Penyempurnaan Tekstil',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10036355', ['nama_jurusan'] => 'Garmen',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10038360', ['nama_jurusan'] => 'Teknik Produksi Minyak dan Gas',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10038365', ['nama_jurusan'] => 'Teknik Pemboran Minyak dan Gas',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10038370', ['nama_jurusan'] => 'Teknik Pengolahan Minyak, Gas dan Petro Kimia',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10038375', ['nama_jurusan'] => 'Teknik Pemboran Minyak',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10038380', ['nama_jurusan'] => 'Teknik Produksi Perminyakan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10040385', ['nama_jurusan'] => 'Geologi Pertambangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10042390', ['nama_jurusan'] => 'Kimia Analisis',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10042395', ['nama_jurusan'] => 'Kimia Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10044400', ['nama_jurusan'] => 'Teknik Kendaraan Ringan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10044405', ['nama_jurusan'] => 'Teknik Sepeda Motor',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11101', ['nama_jurusan'] => 'Teknik Pemintalan Serat Buatan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11102', ['nama_jurusan'] => 'Teknik Pembuatan Benang',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11103', ['nama_jurusan'] => 'Teknik Pembuatan Kain',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11104', ['nama_jurusan'] => 'Teknik Penyempurnaan Tekstil',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11201', ['nama_jurusan'] => 'Teknik Produksi Minyak dan Gas',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11202', ['nama_jurusan'] => 'Teknik Pemboran Minyak dan Gas',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11203', ['nama_jurusan'] => 'Teknik Pengolahan Minyak, Gas dan Petrokimia',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11301', ['nama_jurusan'] => 'Geologi Pertambangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11401', ['nama_jurusan'] => 'Kimia Analisis',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11402', ['nama_jurusan'] => 'Kimia Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11501', ['nama_jurusan'] => 'Teknik Kendaraan Ringan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11502', ['nama_jurusan'] => 'Teknik Sepeda Motor',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11503', ['nama_jurusan'] => 'Teknik Alat Berat',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11504', ['nama_jurusan'] => 'Teknik Perbaikan Bodi Otomotif',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11601', ['nama_jurusan'] => 'Teknik Konstruksi Kapal Baja',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11602', ['nama_jurusan'] => 'Teknik Konstruksi Kapal Kayu',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11603', ['nama_jurusan'] => 'Teknik Konstruksi Kapal Fiberglass',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11604', ['nama_jurusan'] => 'Teknik Instalasi Pemesinan Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11605', ['nama_jurusan'] => 'Teknik Pengelasan Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11606', ['nama_jurusan'] => 'Kelistrikan Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11607', ['nama_jurusan'] => 'Teknik Gambar Rancang Bangun Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11608', ['nama_jurusan'] => 'Interior Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11701', ['nama_jurusan'] => 'Teknik Audio Video',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11703', ['nama_jurusan'] => 'Teknik Elektronika Komunikasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11704', ['nama_jurusan'] => 'Teknik Mekatronika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11705', ['nama_jurusan'] => 'Teknik Ototronik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11801', ['nama_jurusan'] => 'Teknik Energi Hidro',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11802', ['nama_jurusan'] => 'Teknik Energi Surya dan Angin',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11803', ['nama_jurusan'] => 'Teknik Energi Biomassa',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK20101', ['nama_jurusan'] => 'Rekayasa Perangkat Lunak',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK20102', ['nama_jurusan'] => 'Teknik Komputer dan Jaringan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK20103', ['nama_jurusan'] => 'Multimedia',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK20201', ['nama_jurusan'] => 'Teknik Transmisi Telekomunikasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK20202', ['nama_jurusan'] => 'Teknik Suitsing',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK20203', ['nama_jurusan'] => 'Teknik Jaringan Akses',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK30101', ['nama_jurusan'] => 'Keperawatan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK30102', ['nama_jurusan'] => 'Keperawatan Gigi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK30103', ['nama_jurusan'] => 'Analis Kesehatan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK30104', ['nama_jurusan'] => 'Farmasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK30105', ['nama_jurusan'] => 'Farmasi Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10044410', ['nama_jurusan'] => 'Teknik Alat Berat',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10044415', ['nama_jurusan'] => 'Teknik Perbaikan Bodi Otomotif',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10044420', ['nama_jurusan'] => 'Teknik Perbaikan Bodi ',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10044425', ['nama_jurusan'] => 'Otomotif',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046430', ['nama_jurusan'] => 'Teknik Konstruksi Kapal Baja',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046435', ['nama_jurusan'] => 'Teknik Konstruksi Kapal Kayu',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046440', ['nama_jurusan'] => 'Teknik Konstruksi Kapal Fiberglass',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046445', ['nama_jurusan'] => 'Teknik Instalasi Pemesinan Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046450', ['nama_jurusan'] => 'Teknik Pengelasan Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046455', ['nama_jurusan'] => 'Kelistrikan Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046460', ['nama_jurusan'] => 'Teknik Gambar Rancang Bangun Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10046465', ['nama_jurusan'] => 'Interior Kapal',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10048470', ['nama_jurusan'] => 'Teknik Audio Video',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10048480', ['nama_jurusan'] => 'Teknik Elektronika Komunikasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10048485', ['nama_jurusan'] => 'Teknik Mekatronika',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10048490', ['nama_jurusan'] => 'Teknik Ototronik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10050495', ['nama_jurusan'] => 'Teknik Energi Hidro',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10050500', ['nama_jurusan'] => 'Teknik Energi Surya dan Angin',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10050505', ['nama_jurusan'] => 'Teknik Energi Biomassa',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15052510', ['nama_jurusan'] => 'Rekayasa Perangkat Lunak',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15052515', ['nama_jurusan'] => 'Teknik Komputer dan Jaringan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15052520', ['nama_jurusan'] => 'Multi Media',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15054525', ['nama_jurusan'] => 'Teknik Transmisi Telekomunikasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15054530', ['nama_jurusan'] => 'Teknik Suitsing',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15054535', ['nama_jurusan'] => 'Teknik Jaringan Akses',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15056540', ['nama_jurusan'] => 'Teknik Produksi & Penyiaran Program Radio & Pertelevisian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15056545', ['nama_jurusan'] => 'Teknik Produksi dan Penyiaran Program Pertelevisian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '15056550', ['nama_jurusan'] => 'Teknik Produksi dan Penyiaran Program Radio',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20058555', ['nama_jurusan'] => 'Keperawatan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20058560', ['nama_jurusan'] => 'Keperawatan Gigi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20058565', ['nama_jurusan'] => 'Analisis Kesehatan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20058570', ['nama_jurusan'] => 'Farmasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20058575', ['nama_jurusan'] => 'Farmasi Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20060580', ['nama_jurusan'] => 'Pekerjaan Sosial',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20062585', ['nama_jurusan'] => 'Perawatan Sosial',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25064625', ['nama_jurusan'] => 'Agribisnis Tanaman Pangan dan Hortikultura',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25064630', ['nama_jurusan'] => 'Agribisnis Tanaman Perkebunan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25064635', ['nama_jurusan'] => 'Agribisnis Perbenihan dan Kultur Jaringan Tanaman',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25066595', ['nama_jurusan'] => 'Penyuluhan Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25068600', ['nama_jurusan'] => 'Perawatan Kesehatan Ternak',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25068645', ['nama_jurusan'] => 'Agribisnis Ternak Unggas',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25068650', ['nama_jurusan'] => 'Agribisnis Aneka Ternak ',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25070605', ['nama_jurusan'] => 'Pengawasan Mutu',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25072610', ['nama_jurusan'] => 'Agribisnis Perikanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25072615', ['nama_jurusan'] => 'Agribisnis Rumput Laut',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25074620', ['nama_jurusan'] => 'Mekanisasi Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25074675', ['nama_jurusan'] => 'Alat Mesin Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25074680', ['nama_jurusan'] => 'Teknik Tanah dan Air',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25076655', ['nama_jurusan'] => 'Kesehatan Ternak',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25078660', ['nama_jurusan'] => 'Teknologi Pengolahan Hasil Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25078665', ['nama_jurusan'] => 'Teknologi Pengolahan Hasil Perikanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25078670', ['nama_jurusan'] => 'Pengawasan Mutu Hasil Pertanian dan Perikanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25080685', ['nama_jurusan'] => 'Teknik Inventarisasi dan Pemetaan Hutan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25080690', ['nama_jurusan'] => 'Teknik Konservasi Sumberdaya Hutan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25080695', ['nama_jurusan'] => 'Teknik Rehabilitasi dan Reklamasi Hutan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25080700', ['nama_jurusan'] => 'Teknik Produksi Hasil Hutan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25080705', ['nama_jurusan'] => 'Kehutanan (4 Tahun)',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30082710', ['nama_jurusan'] => 'Nautika Kapal Penangkap Ikan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30084720', ['nama_jurusan'] => 'Budidaya Perikanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30084725', ['nama_jurusan'] => 'Budidaya Krustacea',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30084730', ['nama_jurusan'] => 'Budidaya Kekerangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30084735', ['nama_jurusan'] => 'Budidaya Rumput Laut',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30086740', ['nama_jurusan'] => 'Nautika Kapal Niaga',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30086745', ['nama_jurusan'] => 'Teknika Kapal Niaga',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35088750', ['nama_jurusan'] => 'Administrasi Perkantoran',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35090755', ['nama_jurusan'] => 'Akuntansi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35090760', ['nama_jurusan'] => 'Perbankan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35090765', ['nama_jurusan'] => 'Perbankan Syariah',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '35092770', ['nama_jurusan'] => 'Pemasaran',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40094775', ['nama_jurusan'] => 'Usaha Perjalanan Wisata',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40094780', ['nama_jurusan'] => 'Akomodasi Perhotelan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40096785', ['nama_jurusan'] => 'Jasa Boga',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40096790', ['nama_jurusan'] => 'Patiseri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40098795', ['nama_jurusan'] => 'Tata Kecantikan Rambut',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40098800', ['nama_jurusan'] => 'Tata Kecantikan Kulit',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '40100805', ['nama_jurusan'] => 'Tata Busana',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45102825', ['nama_jurusan'] => 'Desain Produksi Interior dan Landscaping',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45104860', ['nama_jurusan'] => 'Desain dan Produksi Kriya Kulit',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45104865', ['nama_jurusan'] => 'Desain dan Produksi Kriya Keramik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40102', ['nama_jurusan'] => 'Agribisnis Tanaman Perkebunan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40103', ['nama_jurusan'] => 'Agribisnis Perbenihan dan Kultur Jaringan Tanaman',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40201', ['nama_jurusan'] => 'Agribisnis Ternak Ruminansia',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40202', ['nama_jurusan'] => 'Agribisnis Ternak Unggas',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40203', ['nama_jurusan'] => 'Agribisnis Aneka Ternak',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40301', ['nama_jurusan'] => 'Kesehatan Hewan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40401', ['nama_jurusan'] => 'Teknologi Pengolahan Hasil Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40402', ['nama_jurusan'] => 'Teknologi Pengolahan Hasil Perikanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40403', ['nama_jurusan'] => 'Pengawasan Mutu Hasil Pertanian dan Perikanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40501', ['nama_jurusan'] => 'Alat Mesin Pertanian',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40502', ['nama_jurusan'] => 'Teknik Tanah dan Air',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40601', ['nama_jurusan'] => 'Teknik Inventarisasi dan Pemetaan Hutan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40602', ['nama_jurusan'] => 'Teknik Konservasi Sumberdaya Hutan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40603', ['nama_jurusan'] => 'Teknik Rehabilitasi dan Reklamasi Hutan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40604', ['nama_jurusan'] => 'Teknik Produksi Hasil Hutan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK50101', ['nama_jurusan'] => 'Nautika Kapal Penangkap Ikan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK50102', ['nama_jurusan'] => 'Teknika Kapal Penangkap Ikan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK50201', ['nama_jurusan'] => 'Budidaya Perikanan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK50202', ['nama_jurusan'] => 'Budidaya Krustacea',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK50203', ['nama_jurusan'] => 'Budidaya Kekerangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK50204', ['nama_jurusan'] => 'Budidaya Rumput Laut',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK50301', ['nama_jurusan'] => 'Nautika Kapal Niaga',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK50302', ['nama_jurusan'] => 'Teknika Kapal Niaga',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK60101', ['nama_jurusan'] => 'Administrasi Perkantoran',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK60201', ['nama_jurusan'] => 'Akuntansi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK60202', ['nama_jurusan'] => 'Perbankan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK60203', ['nama_jurusan'] => 'Perbankan Syariah',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK60301', ['nama_jurusan'] => 'Pemasaran',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK70101', ['nama_jurusan'] => 'Usaha Perjalanan Wisata',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK70102', ['nama_jurusan'] => 'Akomodasi Perhotelan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK70201', ['nama_jurusan'] => 'Jasa Boga',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK70202', ['nama_jurusan'] => 'Patiseri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK70301', ['nama_jurusan'] => 'Tata Kecantikan Rambut',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK70302', ['nama_jurusan'] => 'Tata Kecantikan Kulit',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK70401', ['nama_jurusan'] => 'Tata Busana',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80101', ['nama_jurusan'] => 'Seni Lukis',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80102', ['nama_jurusan'] => 'Seni Patung',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80103', ['nama_jurusan'] => 'Desain Komunikasi Visual',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80104', ['nama_jurusan'] => 'Desain Interior',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80105', ['nama_jurusan'] => 'Animasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80202', ['nama_jurusan'] => 'Desain dan Produksi Kriya Kulit',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80203', ['nama_jurusan'] => 'Desain dan Produksi Kriya Keramik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80204', ['nama_jurusan'] => 'Desain dan Produksi Kriya Logam',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80205', ['nama_jurusan'] => 'Desain dan Produksi Kriya Kayu',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK90101', ['nama_jurusan'] => 'Seni Musik Klasik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK90102', ['nama_jurusan'] => 'Seni Musik Non Klasik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK90201', ['nama_jurusan'] => 'Seni Tari',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK90301', ['nama_jurusan'] => 'Seni Karawitan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK90401', ['nama_jurusan'] => 'Seni Pedalangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45104870', ['nama_jurusan'] => 'Desain dan Produksi Kriya Logam',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45104875', ['nama_jurusan'] => 'Desain dan Produksi Kriya Kayu',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50106880', ['nama_jurusan'] => 'Seni Musik Klasik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50106885', ['nama_jurusan'] => 'Seni Musik Non Klasik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50108890', ['nama_jurusan'] => 'Seni Tari',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50110895', ['nama_jurusan'] => 'Seni Karawitan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50112900', ['nama_jurusan'] => 'Seni Pedalangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50114905', ['nama_jurusan'] => 'Pemeranan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '50114910', ['nama_jurusan'] => 'Tata Artistik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55098810', ['nama_jurusan'] => 'Kecantikan Kulit',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55098815', ['nama_jurusan'] => 'Kecantikan Rambut',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55100820', ['nama_jurusan'] => 'Busana Butik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55116915', ['nama_jurusan'] => 'Seni Teater',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '00000095', ['nama_jurusan'] => 'MIPA',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '10036335', ['nama_jurusan'] => 'Teknik Pemintalan Serat Buatan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '20060575', ['nama_jurusan'] => 'Perawatan Sosial',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25068635', ['nama_jurusan'] => 'Agribisnis Ternak Ruminansia',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25068640', ['nama_jurusan'] => 'Agribisnis Ternak Ruminansia',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10503', ['nama_jurusan'] => 'Teknik Instalasi Pemanfaatan Tenaga Listrik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11002', ['nama_jurusan'] => 'Teknik Pergudangan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK11702', ['nama_jurusan'] => 'Teknik Elektronika Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK30201', ['nama_jurusan'] => 'Pekerjaan Sosial',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK40101', ['nama_jurusan'] => 'Agribisnis Tanaman Pangan dan Hortikultura',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK80201', ['nama_jurusan'] => 'Desain dan Produksi Kriya Tekstil',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK90501', ['nama_jurusan'] => 'Pemeranan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK90502', ['nama_jurusan'] => 'Tata Artistik',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMA00001', ['nama_jurusan'] => 'IPA',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => 'SMA00002', ['nama_jurusan'] => 'IPS',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => 'SMK10701', ['nama_jurusan'] => 'Pemeliharaan dan Perbaikan Motor dan Rangka Pesawat Udara (A',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10703', ['nama_jurusan'] => 'Konstruksi Badan Pesawat Udara (Aircraft Sheet Metal Forming',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK10707', ['nama_jurusan'] => 'Pemeliharaan dan Perbaikan Instrumen Elektronika Pesawat Uda',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => 'SMK20301', ['nama_jurusan'] => 'Teknik Produksi dan Penyiaran Program Radio dan Pertelevisia',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '90900010', ['nama_jurusan'] => 'I - Cerdas Istimewa',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000035', ['nama_jurusan'] => 'Pendidikan Jasmani, Olahraga, dan Kesehatan',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '00000080', ['nama_jurusan'] => 'Pelayanan Prima',['untuk_sma'] => 1,['untuk_smk'] => 0),
array(['jurusan_id'] => '10022190', ['nama_jurusan'] => 'Teknik Pendinginan dan Tata Udara',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10034330', ['nama_jurusan'] => 'Teknik dan Manajemen Transportasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '10048475', ['nama_jurusan'] => 'Teknik Elektronika Industri',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25064', ['nama_jurusan'] => 'Agribisnis Produksi Tanaman',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '25064590', ['nama_jurusan'] => 'Agribisnis Pembibitan dan Kultur Jaringan Tanaman',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '30082715', ['nama_jurusan'] => 'Teknika Kapal Penangkap Ikan',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45104', ['nama_jurusan'] => 'Desain dan Produksi Kriya',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45102830', ['nama_jurusan'] => 'Seni Lukis',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45102835', ['nama_jurusan'] => 'Seni Patung',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45102840', ['nama_jurusan'] => 'Desain Komunikasi Visual',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45102845', ['nama_jurusan'] => 'Desain Interior',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45102850', ['nama_jurusan'] => 'Animasi',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '45104855', ['nama_jurusan'] => 'Desain dan Produksi Kriya Tekstil',['untuk_sma'] => 0,['untuk_smk'] => 1),
array(['jurusan_id'] => '55102825', ['nama_jurusan'] => 'Desain Produksi Interior dan Landscaping',['untuk_sma'] => 0,['untuk_smk'] => 1),
)
?>